name: "Publish"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PUBLISH_DIR: _build
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: '📥 Clone adrestia repo'
        uses: actions/checkout@v2
        with:
          path: adrestia

      - name: '📥 Clone cardano-wallet repo'
        uses: actions/checkout@v2
        with:
          repository: input-output-hk/cardano-wallet
          path: cardano-wallet

      - name: '❄ Install Nix'
        uses: cachix/install-nix-action@v17
        with:
          install_url: https://releases.nixos.org/nix/nix-2.7.0/install
          nix_path: nixpkgs=channel:nixos-21.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://hydra.iohk.io https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - uses: cachix/cachix-action@v10
        with:
          name: adp
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: '❄ Install dependencies'
        run: 'nix develop --command emanote --version'
        working-directory: adrestia

      - name: '🔧 Build docs'
        run: |
          scripts/splice-cardano-wallet-docs.sh $GITHUB_WORKSPACE/cardano-wallet --reflink=auto

          build_dir="$PUBLISH_DIR"
          if [ -n "$PR_NUMBER" ]; then
            build_dir="$build_dir/_pr/$PR_NUMBER"
            nix develop -c yq --in-place -y '.template.baseUrl|=.+"_pr/\(env.PR_NUMBER)/"' docs/.deploy/github/index.yaml
          fi

          mkdir -p "$build_dir"
          nix develop -c emanote --layers "docs;docs/.deploy/github" gen "$build_dir"
        working-directory: adrestia

      - name: '🚀 Deploy to gh-pages'
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: adrestia/${{ env.PUBLISH_DIR }}
          enable_jekyll: false
